services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  redis:
    image: redis:alpine
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  mysql_data:
