services:
  app:
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev # 👈 ESTO ES CLAVE

  nginx:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
